lane :test do
  ci_changelog

  puts ENV['CICL_CI']
  ci_changelog = JSON.dump(ENV['CICL_CHANGELOG'])
  ci_changelog.each do |changelog|
    puts changelog["id"]
    puts changelog["date"]
    puts changelog["title"]
    puts changelog["message"]
    puts changelog["author"]
    puts changelog["email"]
  end
end
